### ISSUE TITLE
Request for help: building psycopg2 OSX wheels

### ISSUE THREAD

**Issue by dvarrazzo** [MacPython/wiki#1]
> We (the MacPython organization) support some other projects building OSX wheels using travis-ci.org; feel free to contact us if you'd like help too.

Hello! I'd like help with that. I've set up Travis CI to build manylinux wheels for psycopg2 (https://github.com/psycopg/psycopg2-wheels). Several OSX users find problems with the dependencies and with the OSX build system so I'd be happy to provide OSX wheels too (https://github.com/psycopg/psycopg2/issues/479).

Thank you very much in advance.

**Comment by matthew-brett** [comment]
Happy to help.  Did you discover [multibuild](https://github.com/matthew-brett/multibuild)?   Examples of rather complicated use at [pillow-wheels](https://github.com/python-pillow/pillow-wheels) and [matplotlib-wheels](https://github.com/MacPython/matplotlib-wheels).  These do OSX and Linux wheels builds, and test them, before uploading to a Rackspace container.  Would you mind taking a look and letting me know if that looks tractable for psycopg?

**Comment by dvarrazzo** [comment]
Hello,

I've seen multibuild, but I found it quite complex. [My solution for manylinux](https://github.com/psycopg/psycopg2/blob/d8b1fbd9052946e585967a3c711702a7417ea0e4/scripts/build-manylinux.sh) is comparatively much simpler.

[The facilities for testing and uploading](https://github.com/psycopg/psycopg2-wheels/blob/master/.travis.yml) are already in place, and uploading happens on our server, we don't need rackspace.

I'm quite happy of the manylinux solution we have; what I wish is someone with OSX experience to build the wheels binary package. If for someone with multibuild experience setting up both manylinux and osx (and maybe win too) is a piece of cake I'd be happy to let them do it. Otherwise an OSX build script to add to our travis solution would be just what needed.

**Comment by matthew-brett** [comment]
Ah - simplicity.

The advantage of multibuild is that you put the logic you have in your manylinux script, into a common `config.sh` file, that works for both manylinux and OSX.  Also, I think you run the tests in the manylinux container, whereas multibuild spins up a new minimal Ubuntu container to run the tests.

**Comment by dvarrazzo** [comment]
I'm sure multibuild has several advantages over my simple solution. I'm happy if someone can help me building OSX wheels: if this is done with multibuild it is an implementation detail for me. Thank you very much.

**Comment by dvarrazzo** [comment]
I think I've done it:

https://github.com/psycopg/psycopg2-wheels/blob/osx/scripts/build_osx.sh
