### ISSUE TITLE
Failure with old version specified on latest macOS for C++ packages

### ISSUE THREAD

**Issue by henryiii** [MacPython/wiki#2]
On the latest macOS (10.14), setting any target below 10.9 fails if you have C++ code in your extension, since libstdc++ is not available at all.

**Comment by matthew-brett** [comment]
Would you mind editing the page you are thinking of?   That would be great help.

**Comment by henryiii** [comment]
I can try. I'm working on https://github.com/scikit-build/scikit-build/issues/362, as well as pretty much being unable to build anything else with C++ in it because < 10.9 is set as a minimum...

Xcode 10 [has removed](https://stackoverflow.com/questions/50694822/xcode-10-ios-12-does-not-contain-libstdc6-0-9) libstdc++ after 5 years of depreciation, at least for iOS. From what I can tell in [the release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes), it seems like 10.6 should still be (in it's last legs) of support. However, I don't seem to be able to build 10.6 C++ code in macOS. (Will wait to edit the Wiki till I know more)

**Comment by matthew-brett** [comment]
I'm sure you know, but the MACOSX_DEPLOYMENT_TARGET is set by Python and distutils, from the Python that you are building for. You can override it by setting the environment variable.  Is there a page on the wiki that suggests using a particular version?  Or is it just that it is showing you that that version (10.6) is the one that Python is using?

**Comment by henryiii** [comment]
I think it's coming from Anaconda Python, since brew python2 and 3, along with the system python, are all 10.14 (10.13 before I did a brew reinstall) - but Anaconda is 10.7. If I force it to build 10.9 on Anaconda, then it works.

The wiki seems to indicate that 10.6 is a good default, and that caused Scikit-build to make it a hard-coded default. I think a note about the need to use 10.9 for C++ would be helpful. The line in the wiki is correct; C packages like Numpy do set 10.6 as the minimum, but they don't have any C++ code in them.

**Comment by matthew-brett** [comment]
Which pages (say 10.6 is a good default)?  Sorry for my laziness ...

At this stage, I think 10.9 is the best default, as you've implied.

**Comment by henryiii** [comment]
https://github.com/MacPython/wiki/wiki/Spinning-wheels says:

> Python.org Pythons all use the 10.6 SDK

> Stuff compiled with the 10.6 SDK should also be compatible with stuff built against later SDK versions (up to and including 10.9)

> As we've seen, the MacPython Python distributions are the best to build against, because they use the 10.6 SDK (and hence are compatible with OSX versions from 10.6) 

Not exactly saying that it is a good default, but very easy to imply from that. Enough so that Scikit-build [wrote](https://scikit-build.readthedocs.io/en/latest/generators.html#default-deployment-target-and-architecture):

> The default deployment target and architecture selected by scikit-build are hard-coded for MacOSX and are respectively 10.6 and x86_64.
> ...
> The information above have been adapted from the excellent Spinning wheels article written by Matthew Brett.

Again, updating the numbers and making sure that the issue with C++ requiring 10.9+ would help a lot.

**Comment by matthew-brett** [comment]
I think you know more about this than me - can you do a few edits to the page?  I'm happy to review.

**Comment by henryiii** [comment]
I've updated the table, text under the table, and added a warning. Can you take a look?

**Comment by henryiii** [comment]
Is there still a MacPython distribution as mentioned at the bottom of the page?

**Comment by matthew-brett** [comment]
Thanks for the changes.  I've extended them a bit.  Do my edits make sense?

**Comment by henryiii** [comment]
Looks good!
