### ISSUE TITLE
Confusion around single-architecture wheel builds

### ISSUE THREAD

**Issue by joerick** [MacPython/wiki#3]
Hello @matthew-brett! 

Bit of a long time listener, first time caller situation here! Firstly, thank you for all your work on Mac wheels, multibuild, delocate etc. It's been enormously helpful for us over at https://github.com/joerick/cibuildwheel/ .

I'm raising an issue about the wiki page https://github.com/MacPython/wiki/wiki/Spinning-wheels#question-will-pip-give-me-a-broken-wheel . I could have changed it myself but I wanted to check with you first to make sure you agree.

The passage I'm interested in is (emphasis mine):

> For pip to accept the wheel as matching its own platform, the platform value has to be compatible with your version of Python and macOS. So, pip will accept wheels specifying 10_6_intel for any version of macOS >= 10.6, with any of i386 or x86_64 or dual-architecture Python. Pip will accept a wheel with platform tags 10_12_x86_64 only on macOS >= 10.12, and for a Python that has single architecture x86_64. **_In particular, Pip will not install this wheel if you are using a dual architecture Python. Most Python.org Pythons and system Python are dual architecture._**

@Legrandin spotted this passage and raised it with us in https://github.com/joerick/cibuildwheel/issues/272. We recently switched to using the `10_9_x86_64` Python builds for Mac wheels, and they were wondering if this would prevent these wheels from installing on the `10_6_intel` builds of Python from Python.org.

However, after [some testing](https://github.com/joerick/cibuildwheel/issues/272#issuecomment-589324175) from @mayeut, it seems this is no longer true (since pip 8). I'd suggest changing the passage to read:

```diff
- Pip will accept a wheel with platform tags 10_12_x86_64 only on macOS >= 10.12, and for a Python that has single architecture x86_64. In particular, Pip will not install this wheel if you are using a dual architecture Python. Most Python.org Pythons and system Python are dual architecture.
+ Pip will accept a wheel with platform tags 10_12_x86_64 only on macOS >= 10.12, on either dual-architecture or single-architecture x86_64 Python.
```

Do you agree with the above, and are you happy for me to make that change?

**Comment by matthew-brett** [comment]
Yes - I do agree.   We discussed this before over at https://github.com/matthew-brett/multibuild/issues/278 - where @robbuckley discovered the same thing as you - so please do make that change.

**Comment by joerick** [comment]
Fantastic! Thank you for confirming. I've made the change and fixed a few other things on the page that looked out-of-date to me. See here for details-

https://github.com/MacPython/wiki/wiki/Spinning-wheels/_compare/3d6f6051c82ce78bc03da28642d337b1852d8ab7...bb74c085ede7c3f0a8130aff7e23558a88880cb4
