### ISSUE TITLE
Merging of two datasets in prodigy

### ISSUE THREAD

**Issue by radhasowjanya** [MacPython/wiki#4]
I have annotated two different files with the same labels but for the second time, I used caps for two labels. After I merged these two models then I got
Label          Precision   Recall   F-Score                                                                                                                             ------------   ---------   ------   -------                                                                                                                          
 designation       77.882   78.125    78.003                                                                                                                             company_name      66.607   59.872    63.060                                                                                                                             end_date          90.377   87.214    88.767                                                                                                                             
from_date         85.447   83.333    84.377                                                                                                                             Company_Name      65.625   45.652    53.846                                                                                                                             Designation       63.366   33.684    43.986                                                                                                                             
I am getting two different designations and company names

how can I resolve this issue so that I can merge these two models without annotating again

**Comment by mattip** [comment]
This is the wrong place to be asking ML questions.
